In [1]:
import numpy as np
import pandas as pd
from apyori import apriori

In [2]:
store_data = pd.read_excel('D:/datamining/data.xls')

In [3]:
store_data.head()

  Barang 1 Barang 2 Barang 3 Barang 4 Barang 5 Barang 6
0     Wine    Chips    Bread   Butter     Milk    Apple
1     Wine      NaN    Bread   Butter     Milk      NaN
2      NaN      NaN    Bread   Butter     Milk      NaN
3      NaN    Chips      NaN      NaN      NaN    Apple
4     Wine    Chips    Bread   Butter     Milk    Apple

In [4]:
store_data.tail()

   Barang 1 Barang 2 Barang 3 Barang 4 Barang 5 Barang 6
17      NaN    Chips      NaN   Butter     Milk    Apple
18     Wine    Chips    Bread   Butter     Milk    Apple
19     Wine      NaN    Bread   Butter     Milk    Apple
20     Wine    Chips    Bread      NaN     Milk    Apple
21      NaN    Chips      NaN      NaN      NaN      NaN

In [9]:
store_data.shape

(22, 6)

In [12]:
records = []
for i in range(0, 22) :
 records.append([str(store_data.values[i,j]) for j in range(0,6)])

In [37]:
association_rules = apriori(records, min_support=0.11, min_confidence=0.9, min_left=1.3, min_lenght=2)
association_results = list(association_rules)

In [38]:
print(len(association_results))

13

In [39]:
print((association_results))

[RelationRecord(items=frozenset({'Wine', 'Apple', 'Bread'}), support=0.45454545454545453, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Apple', 'Wine'}), items_add=frozenset({'Bread'}), confidence=0.9090909090909091, lift=1.25)]), RelationRecord(items=frozenset({'Butter', 'Bread', 'Chips'}), support=0.4090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Bread', 'Chips'}), items_add=frozenset({'Butter'}), confidence=0.9000000000000001, lift=1.3200000000000003), OrderedStatistic(items_base=frozenset({'Butter', 'Chips'}), items_add=frozenset({'Bread'}), confidence=0.9000000000000001, lift=1.2375)]), RelationRecord(items=frozenset({'Wine', 'Butter', 'Bread'}), support=0.45454545454545453, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Butter', 'Wine'}), items_add=frozenset({'Bread'}), confidence=0.9090909090909091, lift=1.25)]), RelationRecord(items=frozenset({'Butter', 'Milk', 'Wine'}), support=0.45454545454545453, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Butter', 'Wine'}), items_add=frozenset({'Milk'}), confidence=0.9090909090909091, lift=1.1764705882352942)]), RelationRecord(items=frozenset({'Milk', 'Wine', 'Chips'}), support=0.4090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Wine', 'Chips'}), items_add=frozenset({'Milk'}), confidence=0.9000000000000001, lift=1.1647058823529415)]), RelationRecord(items=frozenset({'Wine', 'Apple', 'Bread', 'Chips'}), support=0.2727272727272727, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Apple', 'Wine', 'Chips'}), items_add=frozenset({'Bread'}), confidence=1.0, lift=1.375)]), RelationRecord(items=frozenset({'Wine', 'Butter', 'Bread', 'Chips'}), support=0.3181818181818182, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Butter', 'Wine', 'Chips'}), items_add=frozenset({'Bread'}), confidence=1.0, lift=1.375)]), RelationRecord(items=frozenset({'Wine', 'Butter', 'Milk', 'Bread'}), support=0.4090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Wine', 'Butter', 'Bread'}), items_add=frozenset({'Milk'}), confidence=0.9000000000000001, lift=1.1647058823529415), OrderedStatistic(items_base=frozenset({'Butter', 'Milk', 'Wine'}), items_add=frozenset({'Bread'}), confidence=0.9000000000000001, lift=1.2375)]), RelationRecord(items=frozenset({'Butter', 'Apple', 'Wine', 'Bread', 'Chips'}), support=0.22727272727272727, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Butter', 'Apple', 'Wine', 'Chips'}), items_add=frozenset({'Bread'}), confidence=1.0, lift=1.375)]), RelationRecord(items=frozenset({'Apple', 'Wine', 'Bread', 'Milk', 'Chips'}), support=0.22727272727272727, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Milk', 'Apple', 'Wine', 'Chips'}), items_add=frozenset({'Bread'}), confidence=1.0, lift=1.375)]), RelationRecord(items=frozenset({'Butter', 'Wine', 'Bread', 'Milk', 'Chips'}), support=0.2727272727272727, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Butter', 'Milk', 'Wine', 'Chips'}), items_add=frozenset({'Bread'}), confidence=1.0, lift=1.375)]), RelationRecord(items=frozenset({'Butter', 'Wine', 'nan', 'Bread', 'Chips'}), support=0.13636363636363635, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Butter', 'nan', 'Wine', 'Chips'}), items_add=frozenset({'Bread'}), confidence=1.0, lift=1.375)]), RelationRecord(items=frozenset({'Butter', 'Apple', 'Wine', 'Bread', 'Milk', 'Chips'}), support=0.18181818181818182, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Butter', 'Apple', 'Wine', 'Milk', 'Chips'}), items_add=frozenset({'Bread'}), confidence=1.0, lift=1.375)])]

In [40]:
results =[]
for item in association_results:
    pair = item[0]
    items = [x for x in pair]
    
    value0 = str(item[0])
    value1 = str(item[1])
    value2 = str(item[1])[:6]
    value3 = str(item[2][0][2])[:6]
    value4 = str(item[2][0][3])[:6]
    
    rows = (value0,value1,value2,value3,value4)
    results.append(rows)
    label = ['title1','title2','Support','confidence','lift',]
    store_suggestion = pd.DataFrame.from_records(results,columns=label)
    print(store_suggestion)

                                  title1               title2 Support  \
0  frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453  0.4545

  confidence  lift
0     0.9090  1.25
                                    title1               title2 Support  \
0    frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453  0.4545
1  frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091  0.4090

  confidence    lift
0     0.9090    1.25
1     0.9000  1.3200
                                    title1               title2 Support  \
0    frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453  0.4545
1  frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091  0.4090
2   frozenset({'Wine', 'Butter', 'Bread'})  0.45454545454545453  0.4545

  confidence    lift
0     0.9090    1.25
1     0.9000  1.3200
2     0.9090    1.25
                                    title1               title2 Support  \
0    frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453  0.4545
1  frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091  0.4090
2   frozenset({'Wine', 'Butter', 'Bread'})  0.45454545454545453  0.4545
3    frozenset({'Butter', 'Milk', 'Wine'})  0.45454545454545453  0.4545

  confidence    lift
0     0.9090    1.25
1     0.9000  1.3200
2     0.9090    1.25
3     0.9090  1.1764
                                    title1               title2 Support  \
0    frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453  0.4545
1  frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091  0.4090
2   frozenset({'Wine', 'Butter', 'Bread'})  0.45454545454545453  0.4545
3    frozenset({'Butter', 'Milk', 'Wine'})  0.45454545454545453  0.4545
4     frozenset({'Milk', 'Wine', 'Chips'})   0.4090909090909091  0.4090

  confidence    lift
0     0.9090    1.25
1     0.9000  1.3200
2     0.9090    1.25
3     0.9090  1.1764
4     0.9000  1.1647
                                           title1               title2  \
0           frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453
1         frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091
2          frozenset({'Wine', 'Butter', 'Bread'})  0.45454545454545453
3           frozenset({'Butter', 'Milk', 'Wine'})  0.45454545454545453
4            frozenset({'Milk', 'Wine', 'Chips'})   0.4090909090909091
5  frozenset({'Wine', 'Apple', 'Bread', 'Chips'})   0.2727272727272727

  Support confidence    lift
0  0.4545     0.9090    1.25
1  0.4090     0.9000  1.3200
2  0.4545     0.9090    1.25
3  0.4545     0.9090  1.1764
4  0.4090     0.9000  1.1647
5  0.2727        1.0   1.375
                                            title1               title2  \
0            frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453
1          frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091
2           frozenset({'Wine', 'Butter', 'Bread'})  0.45454545454545453
3            frozenset({'Butter', 'Milk', 'Wine'})  0.45454545454545453
4             frozenset({'Milk', 'Wine', 'Chips'})   0.4090909090909091
5   frozenset({'Wine', 'Apple', 'Bread', 'Chips'})   0.2727272727272727
6  frozenset({'Wine', 'Butter', 'Bread', 'Chips'})   0.3181818181818182

  Support confidence    lift
0  0.4545     0.9090    1.25
1  0.4090     0.9000  1.3200
2  0.4545     0.9090    1.25
3  0.4545     0.9090  1.1764
4  0.4090     0.9000  1.1647
5  0.2727        1.0   1.375
6  0.3181        1.0   1.375
                                            title1               title2  \
0            frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453
1          frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091
2           frozenset({'Wine', 'Butter', 'Bread'})  0.45454545454545453
3            frozenset({'Butter', 'Milk', 'Wine'})  0.45454545454545453
4             frozenset({'Milk', 'Wine', 'Chips'})   0.4090909090909091
5   frozenset({'Wine', 'Apple', 'Bread', 'Chips'})   0.2727272727272727
6  frozenset({'Wine', 'Butter', 'Bread', 'Chips'})   0.3181818181818182
7   frozenset({'Wine', 'Butter', 'Milk', 'Bread'})   0.4090909090909091

  Support confidence    lift
0  0.4545     0.9090    1.25
1  0.4090     0.9000  1.3200
2  0.4545     0.9090    1.25
3  0.4545     0.9090  1.1764
4  0.4090     0.9000  1.1647
5  0.2727        1.0   1.375
6  0.3181        1.0   1.375
7  0.4090     0.9000  1.1647
                                              title1               title2  \
0              frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453
1            frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091
2             frozenset({'Wine', 'Butter', 'Bread'})  0.45454545454545453
3              frozenset({'Butter', 'Milk', 'Wine'})  0.45454545454545453
4               frozenset({'Milk', 'Wine', 'Chips'})   0.4090909090909091
5     frozenset({'Wine', 'Apple', 'Bread', 'Chips'})   0.2727272727272727
6    frozenset({'Wine', 'Butter', 'Bread', 'Chips'})   0.3181818181818182
7     frozenset({'Wine', 'Butter', 'Milk', 'Bread'})   0.4090909090909091
8  frozenset({'Butter', 'Apple', 'Wine', 'Bread',...  0.22727272727272727

  Support confidence    lift
0  0.4545     0.9090    1.25
1  0.4090     0.9000  1.3200
2  0.4545     0.9090    1.25
3  0.4545     0.9090  1.1764
4  0.4090     0.9000  1.1647
5  0.2727        1.0   1.375
6  0.3181        1.0   1.375
7  0.4090     0.9000  1.1647
8  0.2272        1.0   1.375
                                              title1               title2  \
0              frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453
1            frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091
2             frozenset({'Wine', 'Butter', 'Bread'})  0.45454545454545453
3              frozenset({'Butter', 'Milk', 'Wine'})  0.45454545454545453
4               frozenset({'Milk', 'Wine', 'Chips'})   0.4090909090909091
5     frozenset({'Wine', 'Apple', 'Bread', 'Chips'})   0.2727272727272727
6    frozenset({'Wine', 'Butter', 'Bread', 'Chips'})   0.3181818181818182
7     frozenset({'Wine', 'Butter', 'Milk', 'Bread'})   0.4090909090909091
8  frozenset({'Butter', 'Apple', 'Wine', 'Bread',...  0.22727272727272727
9  frozenset({'Apple', 'Wine', 'Bread', 'Milk', '...  0.22727272727272727

  Support confidence    lift
0  0.4545     0.9090    1.25
1  0.4090     0.9000  1.3200
2  0.4545     0.9090    1.25
3  0.4545     0.9090  1.1764
4  0.4090     0.9000  1.1647
5  0.2727        1.0   1.375
6  0.3181        1.0   1.375
7  0.4090     0.9000  1.1647
8  0.2272        1.0   1.375
9  0.2272        1.0   1.375
                                               title1               title2  \
0               frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453
1             frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091
2              frozenset({'Wine', 'Butter', 'Bread'})  0.45454545454545453
3               frozenset({'Butter', 'Milk', 'Wine'})  0.45454545454545453
4                frozenset({'Milk', 'Wine', 'Chips'})   0.4090909090909091
5      frozenset({'Wine', 'Apple', 'Bread', 'Chips'})   0.2727272727272727
6     frozenset({'Wine', 'Butter', 'Bread', 'Chips'})   0.3181818181818182
7      frozenset({'Wine', 'Butter', 'Milk', 'Bread'})   0.4090909090909091
8   frozenset({'Butter', 'Apple', 'Wine', 'Bread',...  0.22727272727272727
9   frozenset({'Apple', 'Wine', 'Bread', 'Milk', '...  0.22727272727272727
10  frozenset({'Butter', 'Wine', 'Bread', 'Milk', ...   0.2727272727272727

   Support confidence    lift
0   0.4545     0.9090    1.25
1   0.4090     0.9000  1.3200
2   0.4545     0.9090    1.25
3   0.4545     0.9090  1.1764
4   0.4090     0.9000  1.1647
5   0.2727        1.0   1.375
6   0.3181        1.0   1.375
7   0.4090     0.9000  1.1647
8   0.2272        1.0   1.375
9   0.2272        1.0   1.375
10  0.2727        1.0   1.375
                                               title1               title2  \
0               frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453
1             frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091
2              frozenset({'Wine', 'Butter', 'Bread'})  0.45454545454545453
3               frozenset({'Butter', 'Milk', 'Wine'})  0.45454545454545453
4                frozenset({'Milk', 'Wine', 'Chips'})   0.4090909090909091
5      frozenset({'Wine', 'Apple', 'Bread', 'Chips'})   0.2727272727272727
6     frozenset({'Wine', 'Butter', 'Bread', 'Chips'})   0.3181818181818182
7      frozenset({'Wine', 'Butter', 'Milk', 'Bread'})   0.4090909090909091
8   frozenset({'Butter', 'Apple', 'Wine', 'Bread',...  0.22727272727272727
9   frozenset({'Apple', 'Wine', 'Bread', 'Milk', '...  0.22727272727272727
10  frozenset({'Butter', 'Wine', 'Bread', 'Milk', ...   0.2727272727272727
11  frozenset({'Butter', 'Wine', 'nan', 'Bread', '...  0.13636363636363635

   Support confidence    lift
0   0.4545     0.9090    1.25
1   0.4090     0.9000  1.3200
2   0.4545     0.9090    1.25
3   0.4545     0.9090  1.1764
4   0.4090     0.9000  1.1647
5   0.2727        1.0   1.375
6   0.3181        1.0   1.375
7   0.4090     0.9000  1.1647
8   0.2272        1.0   1.375
9   0.2272        1.0   1.375
10  0.2727        1.0   1.375
11  0.1363        1.0   1.375
                                               title1               title2  \
0               frozenset({'Wine', 'Apple', 'Bread'})  0.45454545454545453
1             frozenset({'Butter', 'Bread', 'Chips'})   0.4090909090909091
2              frozenset({'Wine', 'Butter', 'Bread'})  0.45454545454545453
3               frozenset({'Butter', 'Milk', 'Wine'})  0.45454545454545453
4                frozenset({'Milk', 'Wine', 'Chips'})   0.4090909090909091
5      frozenset({'Wine', 'Apple', 'Bread', 'Chips'})   0.2727272727272727
6     frozenset({'Wine', 'Butter', 'Bread', 'Chips'})   0.3181818181818182
7      frozenset({'Wine', 'Butter', 'Milk', 'Bread'})   0.4090909090909091
8   frozenset({'Butter', 'Apple', 'Wine', 'Bread',...  0.22727272727272727
9   frozenset({'Apple', 'Wine', 'Bread', 'Milk', '...  0.22727272727272727
10  frozenset({'Butter', 'Wine', 'Bread', 'Milk', ...   0.2727272727272727
11  frozenset({'Butter', 'Wine', 'nan', 'Bread', '...  0.13636363636363635
12  frozenset({'Butter', 'Apple', 'Wine', 'Bread',...  0.18181818181818182

   Support confidence    lift
0   0.4545     0.9090    1.25
1   0.4090     0.9000  1.3200
2   0.4545     0.9090    1.25
3   0.4545     0.9090  1.1764
4   0.4090     0.9000  1.1647
5   0.2727        1.0   1.375
6   0.3181        1.0   1.375
7   0.4090     0.9000  1.1647
8   0.2272        1.0   1.375
9   0.2272        1.0   1.375
10  0.2727        1.0   1.375
11  0.1363        1.0   1.375
12  0.1818        1.0   1.375

In [41]:
store_suggestion.describe()

,title1,title2,Support,confidence,lift
count,13,13,13,13,13
unique,13,7,7,3,5
top,"frozenset({'Apple', 'Wine', 'Bread', 'Milk', '...",0.4090909090909091,0.4090,1.0,1.375
freq,1,3,3,7,7

In [42]:
store_suggestion.to_excel('D:/datamining/data_output531.xls')